baseURL = 'https://mad.mikkelricky.dk/'
# https://gohugo.io/getting-started/configuration/#languagecode
# https://gohugo.io/functions/time/format/#localization
languageCode = 'da'
# defaultContentLanguage must be set to localize dates.
# https://discourse.gohugo.io/t/issue-with-multilingual-date-time-format/37575/2
defaultContentLanguage = 'da'

# https://gohugo.io/getting-started/configuration/#enablemissingtranslationplaceholders
enableMissingTranslationPlaceholders = true

title = 'mad.mikkelricky.dk'

# https://gohugo.io/content-management/urls/#permalinks
[permalinks]
  [permalinks.page]
    posts = '/:contentbasename/'
    categories = '/:slug/'
    tags = '/:slug/'

[params]
favicon = 'favicon.ico'

# https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Customization-Styles#custom-css
custom_css = ['site.css']

# https://themes.gohugo.io/themes/gohugo-theme-ananke/#other-hero-settings
# https://tachyons.io/
background_color_class = 'bg-main'

# Index content
# body_classes = 'avenir bg-near-white data-pagefind-body'
# recent_posts_number = 1

  [params.ananke]
    # show_recent_posts = false

[markup]
  [markup.goldmark]
    # duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
    #   footnote = true
    #   linkify = true
    #   linkifyProtocol = 'https'
    #   strikethrough = true
    #   table = true
    #   taskList = true
    #   [markup.goldmark.extensions.cjk]
    #     eastAsianLineBreaks = false
    #     eastAsianLineBreaksStyle = 'simple'
    #     enable = false
    #     escapedSpace = false
    #   [markup.goldmark.extensions.extras]
    #     [markup.goldmark.extensions.extras.delete]
    #       enable = false
    #     [markup.goldmark.extensions.extras.insert]
    #       enable = false
    #     [markup.goldmark.extensions.extras.mark]
    #       enable = false
    #     [markup.goldmark.extensions.extras.subscript]
    #       enable = false
    #     [markup.goldmark.extensions.extras.superscript]
    #       enable = false
    #   [markup.goldmark.extensions.passthrough]
    #     enable = false
    #     [markup.goldmark.extensions.passthrough.delimiters]
    #       block = []
    #       inline = []
    #   [markup.goldmark.extensions.typographer]
    #     apostrophe = '&rsquo;'
    #     disable = false
    #     ellipsis = '&hellip;'
    #     emDash = '&mdash;'
    #     enDash = '&ndash;'
    #     leftAngleQuote = '&laquo;'
    #     leftDoubleQuote = '&ldquo;'
    #     leftSingleQuote = '&lsquo;'
    #     rightAngleQuote = '&raquo;'
    #     rightDoubleQuote = '&rdquo;'
    #     rightSingleQuote = '&rsquo;'
    # [markup.goldmark.parser]
    #   autoHeadingID = true
    #   autoHeadingIDType = 'github'
    #   wrapStandAloneImageWithinParagraph = true
    #   [markup.goldmark.parser.attribute]
    #     block = false
    #     title = true
    # [markup.goldmark.renderHooks]
    #   [markup.goldmark.renderHooks.image]
    #     enableDefault = false
    #   [markup.goldmark.renderHooks.link]
    #     enableDefault = false
    [markup.goldmark.renderer]
      unsafe = true

# https://github.com/davidsneighbour/gohugo-theme-ananke-template-mod
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
